### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by C0kedk** [AutomateAsia/com.ambiclimate#2]
Hi thanks for this,
Bought a second ambi unit and added it to the Homey
integration was great for the first ambi device but when i added the second device both ambi devices became inresponsive through Homey getting timeout when used in flows.. (the official ambi climate app works fine)

any ideas?

**Comment by limkopi78** [comment]
Sorry for the delayed respond. I believe this was already fixed in the latest update.
